name: mctu
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10.14
  - pip=23.3.1
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - pip:
    - opencv-python
    - scikit-image
    - matplotlib
    - tqdm
    - tensorboard
    - tensorboardX
    - ml-collections
    - SimpleITK
    - medpy
    - h5py